spring:
  config:
    activate:
      on-profile: dev

  redis:
    host: redis
    port: 6379

  datasource:
    url: jdbc:mariadb://j6a304.p.ssafy.io:3306/polling
    username: root
    password: root!
    driver-class-name: org.mariadb.jdbc.Driver


  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
sms:
  serviceid: ncp:sms:kr:282615511747:validation_sms
  secretkey: Lf4Oqy1Ebsn9ecds1XC6RopnLodw9NG4z2b3EKLC
  accesskey: oekTboQ7Jao7JPzE8omf
