spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mariadb://j6a304.p.ssafy.io:3306/polling
    username: root
    password: root!
    driver-class-name: org.mariadb.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true