spring:
  profiles:
    active: local
    default: local
    include:
      - core-local
      - core-dev
      - common-local
      - commmon-dev
sms:
  serviceid: test
  accesskey: test
  secretkey: test
