spring:
  profiles:
    active: local
  redis:
    host: 127.0.0.1
    port: 6379


logging:
  file.name: ./PJT-web.log
  level:
    root: INFO
    org.hibernate.SQL: debug
    org.hibernate.type: trace


jwt:
  secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  route:
    authentication:
      path: auth
      refresh: refresh

